url: "http://nikson.org.ua" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "NikS ON" # the name of your site, e.g. ACME Corp.
twitter_url: "https://twitter.com/yegorkowalew"
facebook_url: "https://facebook.com/yegorkowalew"
instagramm_url: "https://instagramm.com/yegorkowalew"
adress_ru: "Производитель ФОП Николаенко С.Г.</br> ТМ Nik.S ON</br>Украина 39500</br>Полтавская обл. г. Карловка</br>ул. Полтавский шлях, 34."
adress_ua: "Виробник ФОП Ніколаєнко С.Г.</br> ТМ Nik.S ON</br>Україна 39500</br>Полтавська обл. г. Карлівка</br>ул. Полтавський шлях, 34."
phone_one: "+38 050 57 85 888"
phone_viber: "+38 067 19 11 933"
mail: "niks.19061966@gmail.com"
footer_about_ru: "Философия вкуса, любви к своему делу, философия жить вкусно! Звоните прямо сейчас или оставляйте заявку и мы свяжемся с Вами в кратчайшее время!"
footer_about_ua: "Філософія смаку, любові до своєї справи, філософія жити смачно! Звоніть прямо зараз обо залишайте заявку і ми зв`яжемося з Вами в найкоротший час!"

menu_ru: [
  {
    text: "Главная",
    url: "/ru",
  },
  {
    text: "Продукция",
    url: "/ru/products",
  },
  {
    text: "О нас",
    url: "/ru/about",
  },
  {
    text: "Контакты",
    url: "/ru/contacts",
  },
]

menu_ua: [
  {
    text: "Головна",
    url: "/",
  },
  {
    text: "Продукція",
    url: "/products/",
  },
  {
    text: "Про нас",
    url: "/about/",
  },
  {
    text: "Контакти",
    url: "/contacts/",
  },
]

collections:
  products:
    output: true

products_categories: [
  {
    categorie: "dried_meat_slices",
    categorie_ru: "Мясные слайсы вяленые",
    categorie_ua: "М'ясні слайси в'ялені",
    url_ua: "/products/dried_meat_slices",
    url_ru: "/ru/products/dried_meat_slices",
  },
  {
    categorie: "sun_dried_meat_slices",
    categorie_ru: "Мясные слайсы сушеные",
    categorie_ua: "М'ясні слайси сушені",
    url_ua: "/products/sun_dried_meat_slices",
    url_ru: "/ru/products/sun_dried_meat_slices",
  },
  {
    categorie: "dried_fruits",
    categorie_ru: "Сушеные фрукты",
    categorie_ua: "Сушені фрукти",
    url_ua: "/products/dried_fruits",
    url_ru: "/ru/products/dried_fruits",
  },
  {
    categorie: "dried_vegetables",
    categorie_ru: "Сушеные овощи",
    categorie_ua: "Сушені овочі",
    url_ua: "/products/dried_vegetables",
    url_ru: "/ru/products/dried_vegetables",
  },
  {
    categorie: "dried_mushrooms",
    categorie_ru: "Сушеные грибы",
    categorie_ua: "Сушені гриби",
    url_ua: "/products/dried_mushrooms",
    url_ru: "/ru/products/dried_mushrooms",
  },
]

popular_text_ua: {
    header_text: "Популярні товари",
    body_text: "Поки Ви шукаєте переваги, наші улюблені клієнти вже насолоджуються смачними м'ясними слайсами, а чергова партія ароматного м'яска вже в'ялиться на нашому виробництві! Повірте, Ви не пошкодуєте. Телефонуйте і замовляйте м'ясні снеки оптом і в роздріб в Україні!",
}

popular_text_ru: {
    header_text: "Популярные товары",
    body_text: "Пока Вы ищете преимущества, наши любимые клиенты уже наслаждаются вкусными мясными слайсами, а очередная
          партия ароматного мяска уже вялится на нашем производстве! Поверьте, Вы не пожалеете. Звоните и заказывайте
          мясные снеки оптом и в розницу в Украине!",
}

slider_bottom: [
  {
    head_ua: "З Nik.S <span>ON</span>",
    head_ru: "С Nik.S <span>ON</span>",
    text_ua: "Дома та в дорозі ВКЛючайся з нами!",
    text_ru: "Дома и в дороге ВКЛючайся с нами!"
  },
  {
    head_ua: "З Nik.S <span>ON</span>",
    head_ru: "С Nik.S <span>ON</span>",
    text_ua: "ВКЛючай смак!",
    text_ru: "ВКЛючай вкус!"
  },
  {
    head_ua: "З Nik.S <span>ON</span>",
    head_ru: "С Nik.S <span>ON</span>",
    text_ua: "ВКЛючай емоції!",
    text_ru: "ВКЛючай эмоции!"
  },
]
  